### ISSUE TITLE
Crashes with float for pitch value

### ISSUE THREAD

**Issue by Robin-Andrews** [manaris/jythonMusic#3]
Even though in music.py it states that a float will be interpreted as a frequency, when I try it, the note plays but then the environment shuts down and disappears. Any chance of fixing this? I'd really like to be able to work with frequencies rather than just MIDI values.

**Comment by manaris** [comment]
It should be fixed now.  Also, see API:

- https://jythonmusic.me/play/#microtonal
- https://jythonmusic.me/note/ (bottom)

Thanks!
