### ISSUE TITLE
extra imports using JEM.jar

### ISSUE THREAD

**Issue by alexgimenez02** [manaris/jythonMusic#6]
I'm trying to create an abstract class with abc library, but when I try to execute using JEM but it does not find this library.
Is there any way to add the required dependencies inside the JEM.jar executable? Maybe modifying the JEM.cfg?

Thanks

**Comment by manaris** [comment]
Hi - first, I would recommend you get the latest code from http://JythonMusic.org.  Just download the distribution and install it.  This will bring Jython up to version 2.7, which I believe includes support for the abc library.
